version: '3.1'

name: ab-shipbee

services:
  db:
    image: mariadb:10.10.2
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ab-shipbee

  api:
    build:
      context: ./src/shipping-service
      dockerfile: ./Dockerfile.development
    volumes:
      - ./src/shipping-service:/app
    ports:
      - 3900:3900
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_DATABASE: ab-shipbee
      DB_HOST: db
      DB_PORT: 3306
      PORT: 3900
      DEVELOPMENT: true
    working_dir: /app
    command: yarn start:dev
